### PR TITLE
Large Refactor to code, added auto configurations, added intake control

### PR DESCRIPTION
**Pull request by ghaeska**
Large code changes, please look at this code, its different, add comments so i can try to explain better.

### CODE REVIEW

**Review by NebVeil — COMMENTED** [review]
What do line 124 and 125 do in this code in fixing robot container in Update constants to include field parameters,

**Review by NebVeil — COMMENTED** [review]
Looks good

**Review by NebVeil — COMMENTED** [review]
looks goods

**Review by Morbidchez — APPROVED** [review]
Looked over and read through all changes, I did not find any issues and Jeramiah was able to answer all of my questions.

**Review by Jerickson05 — APPROVED** [review]
Looks good, no errors found.  The questions that I had were answered with a simple google search, and I had some questions that were from prior that I had answered (Namely the SmartDashboard setup code)

**Review by NebVeil — COMMENTED** [review]
what does lines 95, 96, 97, 98, 99 mean.

**Pull request merged**
